name: Build & Deploy Frontend

on:
  push:
    branches: [ master ]
    paths:
      - 'frontend/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'frontend/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - uses: vafinvr/template-env-action@master
      continue-on-error: true
      env:
        API_URL: ${{ secrets.API_URL }}
      with:
        filename: frontend/.env
    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('frontend/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - run: npm ci
    - run: npm test
    - run: npm run build
    - name: Upload build artifact
      if: github.event == 'push' || github.event == 'workflow_dispatch'
      uses: actions/upload-artifact@v2
      with:
        name: frontend
        path: frontend/build

  deploy:
    if: github.event == 'push' || github.event == 'workflow_dispatch'
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v2
        with:
          name: frontend
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
